### ISSUE TITLE
conda pytorch command not working

### ISSUE THREAD

**Issue by nwmoriarty** [isayevlab/pKa-ANI#3]
Following the instructions but got this...

~> conda install -c conda-forge torchani=2.2.0 cudatoolkit=11.2
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - cudatoolkit=11.2

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by isayev** [comment]
Nigel:
I think pytorch just dropped CUDA toolkit 11.2 from their support. You could probably use 11.3 instead. Alternatively, please use any other version that is still supported: [https://pytorch.org/get-started/locally/](https://pytorch.org/get-started/locally/).
